export const ENV_KEYS = {
  BASE_END_POINT: "https://thebox-dev.portqii.com",
  TOKEN: "VGhlYm94UG9ydHFpaTIwMjJUT0tFTl9TRUNSRVQ=",
  SITE_KEY_GOOGLE: "6Lc6rOAhAAAAAPBNLnyVjqm0S0Ziic9e6EPXDSKv",
  BUYER_PUBLISHED: "Buyer_Published",
  VENDOR_PUBLISHED: "Vendor_Published",
  VENDOR_ADDED: "Vendor_Added",
  ANSWER_EDITED: "Answer_Edited",
  VENDOR_COMMENTED: "Vendor_Commented",
  BUYER_COMMENTED: "Buyer_Commented",
  SIGN_IN_CLICKED: "sign in clicked",
  CREATE_ACCOUNT_CLICKED: "Create account clicked",
  CTA_LINK_CLICKED: "CTA link Pressed",
  VENDOR_NAME_CLICKED: "Vendor name clicked",
  RELATED_TOPIC_CLICKED: "Related topics clicked",
  VIEW_ALL_PRODUCTS: "View all products clicked",
  VIEW_ALL_VENDORS_CLICKED: "View all vendors clicked",
  QUESTION_EDITED: "Question_Edited",
  VENDOR_DELETED: "Vendor_Deleted",
  ALL_CATEGORIES_CLICKED: "all categories-blade clicked",
  ALL_PRODUCTS: "all products",
  SEARCH_CLICKED: "search clicked",
  VENDOR_DELETE_PROPOSAL: "Vendor_Deleted_Proposal",
  BUYER_DELETE_PROPOSAL: "Buyer_Deleted_Proposal",
  FILTERS: "Filters",
  CATEGORIES_CLICKED: "categories clicked",
  BLURB_TITLE_CONTENT_CLICKED: "Blurb title or content clicked",
  BOOKMARK_CLICKED: "bookmark clicked",
  LIKE_CLICKED: "like clicked",
  LIKE_BLURB: "Liked_Blurb",
  COMMENT_USE_CASE: "Like_Use_Case",
  COMMENT_PRODUCT: "Comment_Product",
  COMMENT_BLURB: "Comment_Blurb",
  COMMENT_USE_CASE: "Comment_Use_Case",
  REPLY_PRODUCT: "Reply_Product",
  REPLY_BLURB: "Reply_Blurb",
  REPLY_USE_CASE: "Reply_Use_Case",
  LIKE_PRODUCT: "Liked_Product",
  SHARE_CLICKED: "share clicked",
  PRODUCT_CARD_ACTION_BUTTON: "Product card action button clicked",
  PRODUCT_NAME_CLICKED: "product name clicked",
  FORMOGRAPICS_CLICKED: "Firmographics clicked",
  VENDOR_PRODUCT_CLICKED: "Vendor product clicked",
  VENDOR_CARD_ACTION_BUTTON: "Vendor card action button clicked",
  VIEW_BLURB_CLICKED: "View blurbs clicked",
  VIEW_PRODUCT_CLICKED: "view product clicked",
  VIEW_VEDNOR_CLICKED: "view vendor clicked",
  VENDOR_CARD_CLICKED: "vendor card clicked",
  BUYER_SHARES_PROPOSAL: "Proposal_Shared",
};
