import Head from "next/head";
import { Fragment, useEffect } from "react";
import Home from "../src/home/home";
import { useDispatch } from "react-redux";
import { setCurrentPageFn } from "@/src/store/reducers/globalSlice";
export default function HomePage(props) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setCurrentPageFn("home page"));
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home />
      </main>
    </Fragment>
  );
}

export async function getStaticProps(context) {
  return {
    props: {
      page: "home page",
    }, // will be passed to the page component as props
  };
}
